version: "3.7"

services:
    database:
        image: postgres
        container_name: task_db
        restart: always
        ports: 
            - 5433:5433
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=task-manager
        volumes:
            - pgdata:/data/postgres
    appback:
        build: .
        container_name: task_backend
        restart: always
        ports:
            - 3000:3000
        volumes:
            - appback:/usr/app
        links:
            - database
        depends_on: 
            - database

volumes:
    pgdata:
        driver: local
    appback:
        driver: local
    